export enum GrabberTransform {
	NUMBERIFY = 'NUMBERIFY',
	BOOLEANIFY = 'BOOLEANIFY',
	TRIM = 'TRIM',
	REPLACE = 'REPLACE',
	REPLACE_REGEXP = 'REPLACE_REGEXP',
	PREFIX = 'PREFIX',
	POSTFIX = 'POSTFIX',
	MATCH = 'MATCH',
	EVAL = 'EVAL',
	DECODE = 'DECODE'
}