export enum GrabberTransform {
	NUMBERIFY = 'NUMBERIFY',
	BOOLEANIFY = 'BOOLEANIFY',
	TRIM = 'TRIM',
	REPLACE = 'REPLACE',
	REPLACE_REGEXP = 'REPLACE_REGEXP',
	PREFIX = 'PREFIX',
	POSTFIX = 'POSTFIX'
}